services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: customer-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: my-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
